FROM gradle:jdk17-noble as builder

WORKDIR /workspace/app

COPY . /workspace/app/

RUN ./gradlew build -p ${MODULE}

FROM openjdk:17-slim

RUN groupapp -r appuser && useradd -r -g appuser appuser

WORKDIR /app

COPY from=builder /workspace/app/build/libs/${MODULE}.jar /app/${MODULE}.jar

EXPOSE 8080

USER appuser

ENTRYPOINT ["java", "-jar", "/app/${MODULE}.jar"]



